// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../../types";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * TracingService is the Schema for the tracingservices API
 */
export class TracingService extends pulumi.CustomResource {
    /**
     * Get an existing TracingService resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): TracingService {
        return new TracingService(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:getambassador.io/v3alpha1:TracingService';

    /**
     * Returns true if the given object is an instance of TracingService.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TracingService {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TracingService.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"getambassador.io/v3alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"TracingService" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * TracingServiceSpec defines the desired state of TracingService
     */
    public readonly spec!: pulumi.Output<outputs.getambassador.v3alpha1.TracingServiceSpec | undefined>;

    /**
     * Create a TracingService resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: TracingServiceArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "getambassador.io/v3alpha1";
            resourceInputs["kind"] = "TracingService";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(TracingService.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a TracingService resource.
 */
export interface TracingServiceArgs {
    apiVersion?: pulumi.Input<"getambassador.io/v3alpha1">;
    kind?: pulumi.Input<"TracingService">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * TracingServiceSpec defines the desired state of TracingService
     */
    spec?: pulumi.Input<inputs.getambassador.v3alpha1.TracingServiceSpecArgs>;
}
